services:
  ai:
    build:
      context: .
      dockerfile: docker/ai/Dockerfile
    tty: true
    stop_grace_period: 0s
    # iptablesでip制限を行うため
    privileged: true
    volumes:
      - ./:/var/app
      - type: tmpfs
        target: /var/app/.claude.local
        tmpfs:
          size: 0

      - type: bind
        source: .claude.local/.claude
        target: /home/ubuntu/.claude
        bind:
          create_host_path: false

      - type: bind
        source: .claude.local/.claude.json
        target: /home/ubuntu/.claude.json
        bind:
          create_host_path: false
